services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hkdigitals
      MONGO_INITDB_ROOT_PASSWORD: hkdigitals
    volumes:
      - mongo_data:/data/db  # Persistance des données

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hkdigitals
      ME_CONFIG_MONGODB_ADMINPASSWORD: hkdigitals
      ME_CONFIG_MONGODB_URL: mongodb://hkdigitals:hkdigitals@localhost:27017/
    depends_on:
      - mongo

volumes:
  mongo_data:  # Définition du volume persistant
